name: Handle Release

on:
  release:
    types: [created]

jobs:
  generate:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux targets.
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            target_name: x86_64-linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            target_name: aarch64-linux
          # WebAssembly targets.
          - os: ubuntu-latest
            target: wasm32-unknown-unknown # wasm32-unknown-emscripten?
            target_name: wasm32
          # Windows targets.
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            target_name: x86_64-windows
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            target_name: x86_64-windows-gnu
          # macOS targets.
          - os: macos-latest
            target: x86_64-apple-darwin
            target_name: x86_64-macos
          - os: macos-latest
            target: aarch64-apple-darwin
            target_name: aarch64-macos

    name: "Create release-artifacts target ${{ matrix.target_name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # Targets can be queried with "rustc --print target-list".
      - name: Install dependencies
        run: |
          cargo install cbindgen
          if [ "${{ matrix.target_name }}" == "wasm32" ]; then
              cargo install wasm-bindgen-cli
          fi
          rustup target add ${{ matrix.target }}

      # Targets can be queried with "rustc --print target-list".
      - name: Build
        run: |
          cargo build --lib --release --target=${{ matrix.target }}

      - name: Copy files
        shell: bash
        run: |
          proj_name=${{ github.event.repository.name }}
          mkdir dist
          mkdir dist/lib
          mkdir dist/lib/cmake
          mkdir dist/lib/cmake/${proj_name}
          mkdir dist/include
          cp "CMake/${proj_name}Config.cmake" "dist/lib/cmake/${proj_name}/"
          cbindgen --config cbindgen.toml --crate ${proj_name} --output dist/include/${proj_name}.h
          if [ "${{ matrix.target_name }}" == "wasm32" ]; then
              cp "target/${{ matrix.target }}/release/lib${proj_name}.a" dist/lib/
              cp "target/${{ matrix.target }}/release/${proj_name}.wasm" dist/lib/
          elif [ "$RUNNER_OS" == "Linux" ]; then
              cp "target/${{ matrix.target }}/release/lib${proj_name}.a" dist/lib/
              cp "target/${{ matrix.target }}/release/lib${proj_name}.so" dist/lib/
          elif [ "$RUNNER_OS" == "Windows" ]; then
              mkdir dist/bin
              cp "target/${{ matrix.target }}/release/${proj_name}.lib" dist/lib/
              cp "target/${{ matrix.target }}/release/${proj_name}.dll" dist/bin/
          elif [ "$RUNNER_OS" == "macOS" ]; then
              cp "target/${{ matrix.target }}/release/lib${proj_name}.a" dist/lib/
              cp "target/${{ matrix.target }}/release/lib${proj_name}.dylib" dist/lib/
          fi

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-${{ matrix.target_name }}
          asset_content_type: binary/octet-stream
